plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = mod_group_id
version = mod_version
base { archivesName = mod_id }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            mods {
                pym { source sourceSets.main }
            }
        }
        client {}
        server { args '--nogui' }
    }
}

repositories {
    maven { url = 'https://cursemaven.com' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    implementation fg.deobf("curse.maven:pehkui-319596:${pehkui_file_id}")
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') { expand 'version': project.version }
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
